# vim: ft=yaml.ansible
---
orgname_vault: 'Demo Organization'

controller_validate_certs: false

controller_configuration_async_retries: 30

controller_settings: []

controller_projects: []

controller_organizations:
  - name: "HMI Demo"

controller_inventories: []

controller_inventory_sources: []

controller_credential_types:
  - name: Kubeconfig
    description: kubeconfig file
    kind: cloud
    inputs:
      fields:
        - id: kube_config
          type: string
          label: kubeconfig
          secret: true
          multiline: true
      required:
        - kube_config
    injectors:
      env:
        K8S_AUTH_KUBECONFIG: "{  { tower.filename.kubeconfig }}"
      file:
        template.kubeconfig: "{  { kube_config }}"

  - name: RHSMcredential
    description: RHSM Credentials
    kind: cloud
    inputs:
      fields:
        - id: username
          type: string
          label: RHSM User name
          secret: true
        - id: password
          type: string
          label: RHSM password
          secret: true
      required:
        - username
        - password
    injectors:
      extra_vars:
        rhsm_username: "{  { username }}"
        rhsm_password: "{  { password }}"

  - name: KioskExtraParams
    description: Extra params for Kiosk Container
    kind: cloud
    inputs:
      fields:
        - id: container_extra_params
          type: string
          label: Container Extra params including Gateway Admin password
          secret: true
      required:
        - container_extra_params
    injectors:
      extra_vars:
        container_extra_params: "{  { container_extra_params }}"

controller_templates: []

controller_schedules: []

controller_credentials:
  - name: Kubeconfig
    description: Local Cluster Kubeconfig
    organization: "HMI Demo"
    credential_type: Kubeconfig
    inputs:
      kube_config: "{{ secrets['kubeconfig'] }}"

controller_launch_jobs: []
